### ISSUE TITLE
Retrode 2 does not accept Firmware Flash from 10.11.5, cannot use 'config'

### ISSUE THREAD

**Issue by DoctorDan1986** [cyco/Retrode-Utility#2]
I have a Retrode 2, and the utility to flash it to the most recent firmware appears to work.  I can enter firmware mode, and it will appear to install.  However, 'config' is never accessible after resetting, and the firmware is still the original version.  I know it's been 4 years, but...er, help?

**Comment by cyco** [comment]
Hi there,
glad this thing might still be of use to someone.
It looks like Yosemite made some change to the way usb devices are queried. I updated the code and put together version 0.5. You can grab the new version from http://cyco.github.io/Retrode-Utility/ . Sadly, you can't use the in-app updater since i lost the signing key :/

Let me know if it works.

**Comment by DoctorDan1986** [comment]
Well done, everything works perfectly, and my Retrode is now updated...at least, to v0.18d beta.  Are you aware, however, that a v0.19 beta firmware is now available?  

http://forum.retrode.org/index.php?topic=327.0

If there were a way to have a user-defined folder where users could drop downloaded firmware hex files (or even homemade firmware), that would probably make this a lot more future-proof.

**Comment by cyco** [comment]
Firmware releases are fetched automatically from http://www.retrode.org/documentation/firmware/ but there was a bug in detecting beta versions. I fixed that bug and added an option to chose and install a firmware manually as you suggested. You'll have to update manually again, but the updater has also been fixed so next time you hopefully update form inside the app itself.
